version: "3"
services:
  filebeat:
    image: 'elastic/filebeat:6.5.1'
    restart: always
    volumes:
      - '/home/liangwu/docker/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro'
      - '/opt/tomcat/app-logs:/var/log/tomcat:ro'
      - '/opt/tomcat_01/app-logs:/var/log/tomcat_01:ro'
      - '/opt/tomcat_02/app-logs:/var/log/tomcat_02:ro'
      - '/opt/tomcat_03/app-logs:/var/log/tomcat_03:ro'
      - '/opt/tomcat_04/app-logs:/var/log/tomcat_04:ro'
      - '/opt/tomcat_05/app-logs:/var/log/tomcat_05:ro'
      - '/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro'
