version: "3"
services:
    gitlab-runner:
        image: gitlab/gitlab-runner:latest
        restart: always
        volumes:
            - /home/guoliangwu/docker/gitlab-runner/config:/etc/gitlab-runner:ro
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
