version: "3"

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PWD}
      - MYSQL_PASSWORD=${MYSQL_DB_PWD}
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}

  nextcloud:
    image: nextcloud:fpm-alpine
    volumes:
      - nextcloud:/var/www/html

  nginx:
    build: ./nginx
    depends_on:
      - db
      - nextcloud
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - nextcloud:/var/www/html
